server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carrentalapplication?createDatabaseIfNotExist=true
    username: root
    password: 6204
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: CarRentalApplication

  flyway:
    enabled: true
    locations: classpath:db/migration

  servlet:
    multipart:
      max-file-size: 5MB        # maximum per file
      max-request-size: 20MB    # maximum total per reques

app:
  jwt:
    secret: KZ8x9v3rQ2sH7zLrX5pJ4fW0bN6uS1yE
    expiration-ms: 3600000
  file:
    upload-dir: uploads
    base-url: /uploads
  booking:
    pending-ttl-minutes: 30
    cleanup-interval-ms: 600000     # run cleanup every 600000 ms (10 minutes)
